"""Canonical design, teaching checkpoints and executable acceptance. Standard library only."""
import argparse
import ast
import copy
import hashlib
import json
from pathlib import Path

VERSION = '1.4.0'
MARKER = '<!-- generated by agent-development-coach; edit teaching-state.json/design -->'
DEPENDENCIES = {
    'goal': ['io', 'evaluation', 'delivery'], 'io': ['state', 'nodes', 'evaluation', 'delivery'],
    'model': ['prompt', 'nodes', 'evaluation', 'delivery'], 'prompt': ['nodes', 'evaluation', 'delivery'],
    'tools': ['nodes', 'routing', 'evaluation', 'delivery'],
    'state': ['nodes', 'routing', 'loops', 'memory', 'evaluation', 'delivery'],
    'nodes': ['edges', 'routing', 'evaluation', 'delivery'],
    'edges': ['routing', 'loops', 'evaluation', 'delivery'],
    'routing': ['loops', 'evaluation', 'delivery'], 'loops': ['evaluation', 'delivery'],
    'memory': ['evaluation', 'delivery'], 'knowledge': ['tools', 'nodes', 'evaluation', 'delivery'],
    'control': ['routing', 'evaluation', 'delivery'], 'evaluation': ['delivery'], 'delivery': []}
STAGES = [
    {'id': 'define', 'title': '① 定义任务', 'modules': ['goal', 'io'], 'result': '任务边界、输入输出，谁决定下一步'},
    {'id': 'minimum', 'title': '② 跑通最小闭环', 'modules': ['model', 'prompt', 'state', 'nodes', 'edges'],
     'result': '输入 → 处理 → 输出；代码模式此时生成并运行最小 LangGraph；设计模式逐节点走读'},
    {'id': 'expand', 'title': '③ 按需要扩展', 'modules': ['tools', 'routing', 'loops', 'memory', 'knowledge', 'control'],
     'result': '一次只加一个能力，不需要的结构写明理由并跳过'},
    {'id': 'deliver', 'title': '④ 验收与交付', 'modules': ['evaluation', 'delivery'],
     'result': '检查异常路径、真实文件和理解记录，导出设计与未验证项'}]
QUESTIONS = {
    'goal': ('助手收到范围外的任务，应怎么做？', ['明确边界并说明不能处理', '假装已经完成'], 0),
    'io': ('固定工作流下一步由谁决定？', ['预先定义的规则', '每次都由模型自由决定'], 0),
    'model': ('框架运行加模拟模型证明了什么？', ['框架和本地流程能跑通', '真实模型一定可靠'], 0),
    'prompt': ('提示词的主要作用是什么？', ['指导模型的任务和回答约束', '代替所有程序校验'], 0),
    'tools': ('工具查询失败，应走哪条路？', ['失败处理并如实说明', '把失败当成找到答案'], 0),
    'state': ('下游节点读取的字段需要什么？', ['输入或上游明确提供', '只写字段名称就能有数据'], 0),
    'nodes': ('一个节点应该记录什么？', ['读什么、做什么、写什么', '只有名称即可'], 0),
    'edges': ('只有节点没有连线，图能完整运行吗？', ['不能，必须连接入口和出口', '能，框架会猜路线'], 0),
    'routing': ('条件分支需要考虑什么？', ['正常、异常和兜底出口', '只考虑成功分支'], 0),
    'loops': ('循环需要什么才能安全结束？', ['次数上限和真实退出分支', '图上画一个出口就足够'], 0),
    'memory': ('长期记忆和单次运行状态一样吗？', ['不同，需要明确保存范围和生命周期', '一样，自动永久保存'], 0),
    'knowledge': ('没有检索到资料时应该怎么回答？', ['说明缺少依据或请求补充', '编造资料来源'], 0),
    'control': ('人工确认应该放在何处？', ['需要人作决定的步骤之前', '操作全部完成以后'], 0),
    'evaluation': ('预期结果可以算实际验证吗？', ['不可以，必须保留真实执行结果', '可以，只要看起来合理'], 0),
    'delivery': ('修改设计以后，原代码是否自动同步？', ['不会，必须实现并重新验证', '会，保存图就等于改代码'], 0)}

def fingerprint(value):
    return hashlib.sha256(json.dumps(value, ensure_ascii=False, sort_keys=True).encode()).hexdigest()

def mastery_hash(module):
    return fingerprint({'decision': module.get('decision', ''), 'exercise': module.get('exercise', {})})

def normalize(source, previous=None):
    s = copy.deepcopy(source)
    d = s.setdefault('design', {})
    d.setdefault('version', 1)
    d.setdefault('component_decisions', {m['id']: m.get('decision', '') for m in s['modules']})
    d.setdefault('system', {'kind': 'undecided', 'reason': ''})
    d.setdefault('graph', copy.deepcopy(s.get('agent_graph', {'nodes': [], 'edges': []})))
    d.setdefault('contracts', {'inputs': [], 'outputs': [], 'state_fields': {}, 'nodes': {}, 'tools': {}, 'routes': {}, 'loop_limits': {}, 'tests': []})
    if previous:
        old = normalize(previous)
        for m in s['modules']:
            key = m['id']; before = old['design']['component_decisions'].get(key, '')
            canonical = d['component_decisions'].get(key, '')
            mirror = m.get('decision', '')
            if mirror != before and canonical != before and mirror != canonical:
                raise ValueError(f'{key} 的设计正文与结构记录冲突，请保留一个明确决定。')
            if mirror != before and canonical == before:
                d['component_decisions'][key] = mirror
        if s.get('agent_graph') != old['agent_graph']:
            if d['graph'] != old['design']['graph'] and d['graph'] != s['agent_graph']:
                raise ValueError('业务图与规范图冲突，请合并后保存。')
            d['graph'] = copy.deepcopy(s['agent_graph'])
    s['agent_graph'] = copy.deepcopy(d['graph'])
    s['decisions'] = copy.deepcopy(d['component_decisions'])
    for m in s['modules']:
        m['decision'] = d['component_decisions'].get(m['id'], '')
        q = QUESTIONS.get(m['id'], ('说明本步的作用', [], None))
        # Assessment is an objective concept check. Transfer to the student's own design requires teacher review.
        m.setdefault('exercise', {'question': q[0], 'options': q[1], 'correct': q[2],
            'feedback': '回看本步的职责、输入输出和异常处理，再试一次。'})
        m.setdefault('mastery', {'status': 'pending', 'answer': None, 'reason': '', 'feedback': ''})
    s['stages'] = copy.deepcopy(STAGES)
    s.setdefault('sync', {'implementation_pending': [], 'reviews': []})
    s['teaching_version'] = VERSION
    return s

def semantic_graph(g):
    return {'nodes': [{k: v for k, v in n.items() if k not in ('x', 'y', 'label')} for n in g['nodes']],
            'edges': [{k: v for k, v in e.items() if k != 'label'} for e in g['edges']]}

def execution_hash(design):
    semantic = copy.deepcopy(design)
    semantic['graph'] = semantic_graph(semantic['graph'])
    return fingerprint(semantic)

def affect(s, ids, reason, business=True):
    if not ids: return
    affected = set(ids)
    if business:
        for key in ids:
            affected.update(DEPENDENCIES.get(key, []))
    for m in s['modules']:
        if m['id'] in affected:
            m['presentation_status'] = 'review'
            if business:
                if m['status'] in ('done', 'skipped'): m['status'] = 'review'
                m['mastery'] = {**m['mastery'], 'status': 'review', 'feedback': reason}
    if business:
        s['design_status'] = '需复核'
        s['sync']['implementation_pending'] = sorted(set(s['sync']['implementation_pending']) | affected)
    s['sync']['reviews'] = (s['sync']['reviews'] + [{'modules': sorted(affected), 'reason': reason,
                                                   'kind': '业务变更' if business else '讲解变更'}])[-40:]

def reconcile(source, previous):
    s = normalize(source, previous); old = normalize(previous)
    for key, value in s['design']['component_decisions'].items():
        if value != old['design']['component_decisions'].get(key):
            affect(s, [key], f'{key} 的设计决定改变，需要核对依赖结构与实现。')
    if semantic_graph(s['agent_graph']) != semantic_graph(old['agent_graph']):
        affect(s, ['nodes', 'edges', 'routing'], '业务节点或连线改变。')
    elif [{**n, 'x': 0, 'y': 0} for n in s['agent_graph']['nodes']] != [{**n, 'x': 0, 'y': 0} for n in old['agent_graph']['nodes']] or [e.get('label') for e in s['agent_graph']['edges']] != [e.get('label') for e in old['agent_graph']['edges']]:
        affect(s, ['nodes', 'edges'], '图示文字改变，请核对讲解。', False)
    for key, ids in {'inputs': ['io'], 'outputs': ['io'], 'state_fields': ['state'], 'nodes': ['nodes'],
                     'tools': ['tools'], 'routes': ['routing'], 'loop_limits': ['loops'], 'tests': ['evaluation']}.items():
        if s['design']['contracts'].get(key) != old['design']['contracts'].get(key):
            affect(s, ids, f'{key} 契约改变。')
    if s['design']['system'] != old['design']['system']:
        affect(s, ['io', 'nodes', 'edges'], '工作流/智能体路线改变。')
    return s

def derived(s):
    d = s['design']; graph = ['flowchart TD']
    for n in d['graph']['nodes']:
        # Labels are escaped as numeric entities, never executable Mermaid syntax.
        label = ''.join(c if c.isalnum() or c in ' _' else f'&#{ord(c)};' for c in str(n.get('label', n['id'])))
        graph.append(f'  {n["id"]}["{label}"]')
    for e in d['graph']['edges']: graph.append(f'  {e["from"]} --> {e["to"]}')
    md = MARKER + '\n# 智能体设计摘要\n\n'
    md += f'架构选择：{d["system"]["kind"]}\n\n理由：{d["system"].get("reason", "")}\n\n'
    for m in s['modules']: md += f'## {m["title"]}\n\n{m["decision"] or "尚未决定"}\n\n'
    return {'agent-design/design-summary.md': md,
        'agent-design/design-contracts.md': MARKER + '\n# 结构化契约\n\n```json\n' + json.dumps(d['contracts'], ensure_ascii=False, indent=2) + '\n```\n',
        'agent-design/architecture.mmd': '%% generated by agent-development-coach\n' + '\n'.join(graph) + '\n',
        'agent-design/design-spec.json': json.dumps({'generated_by': 'agent-development-coach', 'design': d}, ensure_ascii=False, indent=2)}

def safe_file(root, relative):
    if not isinstance(relative, str) or '\\' in relative or any(p.startswith('.') for p in Path(relative).parts):
        return None
    target = (Path(root) / relative).resolve()
    return target if not Path(relative).is_absolute() and target.is_relative_to(Path(root).resolve()) else None

def audit(source, root=None):
    s = normalize(source); d = s['design']; c = d['contracts']; issues = []
    def issue(module, message): issues.append({'module': module, 'message': message})
    if d['system']['kind'] not in ('workflow', 'agent') or not d['system'].get('reason'):
        issue('io', '选择固定工作流或模型动态决策，并解释原因。')
    nodes = {n['id'] for n in d['graph']['nodes']}; edges = d['graph']['edges']
    adj = {n: set() for n in nodes}; rev = {n: set() for n in nodes}
    for e in edges:
        if e['from'] in nodes and e['to'] in nodes:
            adj[e['from']].add(e['to']); rev[e['to']].add(e['from'])
        else: issue('edges', '连线引用了不存在的节点。')
    def reach(start, links):
        seen = set(); todo = [start]
        while todo:
            n = todo.pop()
            if n in seen: continue
            seen.add(n); todo.extend(links.get(n, set()) - seen)
        return seen
    if not {'START', 'END'} <= nodes: issue('edges', '业务图必须有 START 和 END。')
    if adj.get('END'): issue('edges', 'END 不应有后续连线。')
    reachable = reach('START', adj); exits = reach('END', rev)
    for n in sorted(nodes):
        if n not in reachable: issue('edges', f'{n} 从入口不可达。')
        if n not in exits: issue('edges', f'{n} 无法抵达出口。')
    fields = c.get('state_fields', {}); inputs = c.get('inputs', []); outputs = c.get('outputs', [])
    if not inputs or not outputs: issue('io', '定义输入字段和输出字段。')
    for f in inputs + outputs:
        if f not in fields: issue('state', f'{f} 没有状态字段类型。')
    contracts = c.get('nodes', {})
    if d['system']['kind'] == 'agent':
        dynamic = d['system'].get('dynamic_node')
        field = d['system'].get('decision_field')
        if dynamic not in contracts or not field or field not in contracts.get(dynamic, {}).get('writes', []) or not any(r.get('field') == field for r in c.get('routes', {}).get(dynamic, [])):
            issue('io', '动态智能体必须绑定真实模型决策节点 dynamic_node 和决策字段 decision_field，并由该字段选择工具或结束。')
    initial = set(inputs) | {k for k, v in fields.items() if isinstance(v, dict) and 'default' in v and k not in outputs}
    # Definite field availability: intersection of every predecessor, including cyclic paths.
    available = {n: set(fields) for n in nodes}; available['START'] = initial
    for _ in range(max(1, len(nodes) * 2)):
        changed = False
        for n in nodes - {'START'}:
            incoming = [available[p] | set(contracts.get(p, {}).get('writes', [])) for p in rev[n]]
            new = set.intersection(*incoming) if incoming else set()
            if new != available[n]: available[n] = new; changed = True
        if not changed: break
    for n in sorted(nodes - {'START', 'END'}):
        nc = contracts.get(n)
        if not isinstance(nc, dict): issue('nodes', f'{n} 缺少输入、输出与源文件契约。'); continue
        for f in nc.get('reads', []) + nc.get('writes', []):
            if f not in fields: issue('state', f'{n} 使用未定义字段 {f}。')
        for f in nc.get('reads', []):
            if f not in available[n]: issue('state', f'{n} 的 {f} 并非所有上游路径都提供。')
        if (not nc.get('source') or not nc.get('function')) and s.get('delivery') not in ('仅设计', '只做设计'): issue('nodes', f'{n} 没有实现文件和函数绑定。')
        elif root and s.get('delivery') not in ('仅设计', '只做设计'):
            p = safe_file(root, nc['source'])
            if not p or not p.is_file(): issue('nodes', f'{n} 的源文件不存在。')
            else:
                try:
                    functions = {v.name for v in ast.parse(p.read_text(encoding='utf-8-sig')).body if isinstance(v, (ast.FunctionDef, ast.AsyncFunctionDef))}
                    if nc['function'] not in functions: issue('nodes', f'{n} 的绑定函数在源文件中不存在。')
                except (SyntaxError, UnicodeError): issue('nodes', f'{n} 的源文件不能作为有效 Python 解析。')
        if len(adj[n]) > 1:
            rules = c.get('routes', {}).get(n, [])
            if {r.get('to') for r in rules} != adj[n] or sum(r.get('op') == 'default' for r in rules) != 1:
                issue('routing', f'{n} 的分支必须覆盖所有连线并有唯一兜底。')
            for r in rules:
                if r.get('op') not in ('eq', 'empty', 'nonempty', 'default'): issue('routing', f'{n} 使用不支持的判断操作。')
                if r.get('op') != 'default' and r.get('field') not in fields: issue('routing', f'{n} 的判断字段不存在。')
    for f in outputs:
        if f not in available.get('END', set()): issue('io', f'并非所有结束路径都产生 {f}。')
    cyclic = {n for n in nodes if any(n in reach(to, adj) for to in adj[n])}
    limits = c.get('loop_limits', {})
    for n in sorted(cyclic):
        guard = limits.get(n, {})
        if not isinstance(guard.get('max'), int) or guard.get('max', 0) <= 0 or guard.get('counter') not in fields or guard.get('exit') not in adj[n] or guard.get('counter') not in contracts.get(n, {}).get('writes', []):
            issue('loops', f'{n} 的循环缺少可执行次数上限、计数字段更新或真实退出连线。')
    for name, tool in c.get('tools', {}).items():
        if not tool.get('input') or not tool.get('output') or not tool.get('failure') or tool.get('node') not in nodes:
            issue('tools', f'{name} 缺少输入、输出、失败行为或调用节点。')
    needed = {'normal', 'invalid', 'missing', 'no_result', 'tool_error', 'out_of_scope'}
    cases = {t.get('case') for t in c.get('tests', []) if t.get('expected')}
    if needed - cases: issue('evaluation', '缺少验收场景：' + '、'.join(sorted(needed - cases)))
    for m in s['modules']:
        if m['status'] not in ('done', 'skipped') or not m['decision'].strip() or not m.get('check'):
            issue(m['id'], '决定、通过依据或不采用理由不完整。')
        if m.get('presentation_status') != 'shown': issue(m['id'], '成果尚未展示。')
        mastery = m.get('mastery', {})
        correct = m['exercise'].get('correct')
        if mastery.get('status') != 'passed' or (correct is not None and mastery.get('answer') != correct) or not mastery.get('reason', '').strip() or mastery.get('content_hash') != mastery_hash(m) or not mastery.get('review_basis'):
            issue(m['id'], '当前设计的理解检查及迁移解释尚未通过。')
        artifacts = m.get('artifacts', [])
        if not artifacts: issue(m['id'], '没有实际成果记录。')
        for a in artifacts:
            if a.get('outdated') or not a.get('content') or not a.get('explanations'): issue(m['id'], '成果正文或讲解缺失/过期。')
            if root:
                p = safe_file(root, a.get('path', ''))
                if not p or not p.is_file(): issue(m['id'], '成果文件不存在：' + str(a.get('path')))
                elif str(a.get('content', '')).replace('\r\n', '\n').strip() not in p.read_text(encoding='utf-8-sig').replace('\r\n', '\n'):
                    issue(m['id'], '成果展示与实际文件不一致：' + a['path'])
    if s['sync']['implementation_pending'] and s.get('delivery') not in ('仅设计', '只做设计'):
        issue('delivery', '新设计尚有未应用到代码的结构：' + '、'.join(s['sync']['implementation_pending']))
    if any('阻断' in str(q) for q in s.get('open_questions', [])): issue('delivery', '还有阻断交付的未决问题。')
    if root:
        for name, text in derived(s).items():
            p = safe_file(root, name)
            if not p or not p.is_file() or p.read_text(encoding='utf-8') != text:
                issue('delivery', name + ' 尚未同步，执行设计同步后再验收。')
    return {'passed': not issues, 'issues': issues, 'design_hash': execution_hash(d),
            'scope': '设计与学习验收；真实模型质量另行验证'}

def grade(source, module_id, answer, reason):
    s = normalize(source); m = next(m for m in s['modules'] if m['id'] == module_id)
    correct = m['exercise'].get('correct')
    ok = correct is None or answer == correct
    m['mastery'] = {'status': 'awaiting_review' if ok and str(reason).strip() else 'retry', 'answer': answer,
        'reason': str(reason), 'content_hash': mastery_hash(m),
        'feedback': '概念题通过。还需教练核对你对自己项目的解释。' if ok and str(reason).strip() else (m['exercise']['feedback'] if not ok else '请用自己的项目说明原因，再提交。')}
    return s

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--project', type=Path, required=True)
    parser.add_argument('--sync', action='store_true')
    parser.add_argument('--audit', action='store_true')
    parser.add_argument('--review', help='教练复核理解：填写模块 ID')
    parser.add_argument('--applied', help='教练确认已应用到实现：逗号分隔模块 ID')
    parser.add_argument('--basis', help='具体复核依据，不能只填“通过”')
    args = parser.parse_args()
    from workbench import Project
    p = Project(args.project)
    s = p.state()
    if args.review or args.applied:
        if not args.basis or len(args.basis.strip()) < 12: parser.error('提供具体的学生解释/文件改动/实际验证依据，至少 12 字。')
        if args.review:
            m = next((m for m in s['modules'] if m['id'] == args.review), None)
            if not m or m['mastery']['status'] != 'awaiting_review': parser.error('先完成概念题并提交自己的解释。')
            m['mastery'].update(status='passed', review_basis=args.basis, content_hash=mastery_hash(m))
        if args.applied:
            ids = args.applied.split(',')
            if any(key not in {m['id'] for m in s['modules']} for key in ids): parser.error('未知结构 ID。')
            current_hash = execution_hash(s['design'])
            evidence = [r for r in s.get('runs', []) if r.get('mode') != 'design' and r.get('status') == 'executed' and r.get('design_hash') == current_hash]
            if s.get('delivery') not in ('仅设计', '只做设计') and not evidence: parser.error('没有当前设计的实际框架运行证据，不能确认实现。')
            for r in evidence:
                for path, sha in r.get('source_hashes', {}).items():
                    file = safe_file(p.root, path)
                    if not file or not file.is_file() or hashlib.sha256(file.read_bytes()).hexdigest() != sha:
                        parser.error('运行后源代码改变，需要重新执行。')
            s['sync']['implementation_pending'] = [key for key in s['sync']['implementation_pending'] if key not in ids]
            s['sync'].setdefault('applications', []).append({'modules': ids, 'basis': args.basis, 'design_hash': current_hash})
        p.save_state({'state': s, 'expected_revision': p.snapshot()['revision']})
    if args.sync:
        p.save_state({'state': p.state(), 'expected_revision': p.snapshot()['revision']})
    print(json.dumps(audit(p.state(), p.root), ensure_ascii=False, indent=2))

if __name__ == '__main__': main()
